//when i open the map thats longitude and latitude will show, center and zoom that i choose. 
let mapOptions = {
  center:[31.625, 34.607],
  zoom:8
}

//creating the map with leafleat api class. the first parameter is 'map' that is the id that we gave to the div, and second paramter is mapOptions that when we open the map its at 
// center:[31.625, 34.607] and zoom:8
let map = new L.map('map' , mapOptions);

//we load the map with openstreetmap
let layer = new L.TileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png');
map.addLayer(layer);

// let marker = new L.Marker([32.99676, 35.68700]);
// marker.addTo(map);

//change the regular icon
let customIcon = {
  iconUrl:"images/marker3.png",
  iconSize:[40,40]
}

let myIcon = L.icon(customIcon);


let locations = [
  {
      "id": 1,
      "lat": 32.99671,
      "long": 35.68698,
      "title": "שם:מטווח אמיר שושני(נשק הגליל)",
      "popupContent": "מחוז:צפון",
      "popupContent1": "יישוב:קצרין",
      "popupContent2": "כתובת:מרכז מסחרי קצרין",
      "popupContent3": "טלפון:04-6997505",
      "popupContent4": "סוג אימון:פרטי+מאבטחים",
      "url":"<b>אתר:</b> <span>אין<span>",
  },
  {
      "id": 2,
      "lat": 33.02254,
      "long": 35.58370,
      "title": "שם:מטווח טריגר איילת השחר",
      "popupContent": "מחוז:צפון",
      "popupContent1": "יישוב:קיבוץ איילת השחר",
      "popupContent2": "כתובת:קיבוץ איילת השחר",
      "popupContent3": "טלפון:052-6707909",
      "popupContent4": "סוג אימון:פרטי+מאבטחים",
      "url":"<b>אתר:</b><a href='https://www.trigger-at.com' target=_blank>לחץ כאן</a>",
  },
  {
      "id": 3,
      "lat": 32.9863,
      "long": 35.1660,
      "title": "שם:מטווח מטה אשר(מכולה)",
      "popupContent": "מחוז:חיפה",
      "popupContent1": "יישוב:מטה אשר",
      "popupContent2": "כתובת:על כביש 8721,דרך לג'ת",
      "popupContent3": "טלפון:054-6802438",
      "popupContent4": "סוג אימון:פרטי",
      "url":"<b>אתר:</b> <span>אין<span>", 
  },
  {
      "id": 4,
      "lat": 32.99373,
      "long": 35.13677,
      "title": "שם:מטווח מועצה אזורית מטה אשר",
      "popupContent": "מחוז:חיפה",
      "popupContent1": "יישוב:נתיב השיירה",
      "popupContent2": "כתובת:נתיב השיירה",
      "popupContent3": "טלפון:054-7482620",
      "popupContent4": "סוג אימון:פרטי+מאבטחים",
      "url":"<b>אתר:</b> <span>אין<span>",
  },
  {
     "id": 5,
     "lat": 32.91049,
     "long": 35.30388,
     "title": "שם:קליבר 3 בעמ",
     "popupContent": "מחוז:צפון",
     "popupContent1": "יישוב:כרמיאל",
     "popupContent2": "כתובת:מורד הגיא 9",
     "popupContent3": "טלפון:052-6707909",
     "popupContent4": "סוג אימון:פרטי+מאבטחים",
     "url":"<b>אתר:</b><a href='https://www.caliber3range.com' target=_blank>לחץ כאן</a>",
},
 {
   "id": 6,
   "lat": 32.86572,
   "long": 35.25202,
   "title": "שם:מועצה אזורית משגב",
   "popupContent": "מחוז:צפון",
   "popupContent1": "יישוב:עצמון(משגב)",
   "popupContent2": "כתובת:עצמון(משגב)",
   "popupContent3": "טלפון:04-9902381",
   "popupContent4": "סוג אימון:פרטי",
   "url":"<b>אתר:</b> <span>אין<span>",
   
},
{
  "id": 7,
  "lat": 32.8107,
  "long": 35.1744,
  "title": "שם:מטווח המרכז הצפוני לקליעה בעמ",
  "popupContent": "מחוז:צפון",
  "popupContent1": "יישוב:שפרעם",
  "popupContent2": "כתובת:שכונת אלמידאן",
  "popupContent3": "טלפון:04-9504477",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 8,
  "lat": 32.82067,
  "long": 34.99840,
  "title": "שם:מטווחי הצפון ק.א בעמ",
  "popupContent": "מחוז:חיפה",
  "popupContent1": "יישוב:חיפה",
  "popupContent2": "כתובת:הנמל 38",
  "popupContent3": "טלפון:04-8675316",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 9,
  "lat": 32.6499,
  "long": 35.5701,
  "title": "שם:מטווח מוא'ז עמק הירדן",
  "popupContent": "מחוז:צפון",
  "popupContent1": "יישוב:אשדות יעקב",
  "popupContent2": "כתובת:אשדות יעקב",
  "popupContent3": "טלפון:04-6757640",
  "popupContent4": "סוג אימון:פרטי",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 10,
  "lat": 32.66348,
  "long": 35.25821,
  "title": "שם:נשק הצפון+קליבר 3 בעמ",
  "popupContent": "מחוז:צפון",
  "popupContent1": "יישוב:קיבוץ גיניגר",
  "popupContent2": "כתובת:קיבוץ גיניגר",
  "popupContent3": "טלפון:050-4700047",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b><a href='https://www.caliber3range.com' target=_blank>לחץ כאן</a>",
},
{
  "id": 11,
  "lat": 32.60685,
  "long": 35.29414,
  "title": "שם:נשק הצפון ר.2002 בעמ",
  "popupContent": "מחוז:צפון",
  "popupContent1": "יישוב:עפולה",
  "popupContent2": "כתובת:קהילת ציון 14",
  "popupContent3": "טלפון:04-6573573",
  "popupContent4": "סוג אימון:פרטי",
  "url":"<b>אתר:</b><a href='https://northarm.co.il/' target=_blank>לחץ כאן</a>",
},
{
  "id": 12,
  "lat": 32.59198,
  "long": 35.07901,
  "title": "שם:מ.א רוי יעוץ והדרכה בעמ",
  "popupContent": "מחוז:צפון",
  "popupContent1": "יישוב:קיבוץ דליה",
  "popupContent2": "כתובת:קיבוץ דליה",
  "popupContent3": "טלפון:04-9591533",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 13,
  "lat": 32.45205,
  "long": 34.95020,
  "title": "שם:א.ע אל-עם יזמות בעמ",
  "popupContent": "מחוז:חיפה",
  "popupContent1": "יישוב:גן שמואל",
  "popupContent2": "כתובת:גן שמואל",
  "popupContent3": "טלפון:04-6360017",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 14,
  "lat": 32.43475,
  "long": 34.92233,
  "title": "שם:טיטניום בעמ",
  "popupContent": "מחוז:חיפה",
  "popupContent1": "יישוב:חדרה",
  "popupContent2": "כתובת:הגבורים 72",
  "popupContent3": "טלפון:04-6341646",
  "popupContent4": "סוג אימון:פרטי",
  "url":"<b>אתר:</b> <span>אין<span>",
  
},
{
  "id": 15,
  "lat": 32.32857,
  "long": 34.85733,
  "title": "שם:מטווח העיר סחר בינלאומי בעמ",
  "popupContent": "מחוז:מרכז",
  "popupContent1": "יישוב:נתניה",
  "popupContent2": "כתובת:הרצל 53",
  "popupContent3": "טלפון:09-8611122",
  "popupContent4": "סוג אימון:פרטי",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 16,
  "lat": 32.18310,
  "long": 34.92403,
  "title": "שם:מרכז הקליעה ע'ש מיכה אלמוג",
  "popupContent": "מחוז:מרכז",
  "popupContent1": "יישוב:כפר סבא",
  "popupContent2": "כתובת:בן יהודה 69",
  "popupContent3": "טלפון:09-7665533",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 17,
  "lat": 32.16756,
  "long": 34.82823,
  "title": "שם:המרכז האולימפי הלאומי לקליעה",
  "popupContent": "מחוז:מרכז",
  "popupContent1": "יישוב:הרצליה",
  "popupContent2": "כתובת:זבוטינסקי 85",
  "popupContent3": "טלפון:09-9547311",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 18,
  "lat": 32.17444,
  "long": 35.09128,
  "title": "שם:מטווח קרני שומרון - החברה הכלכלי",
  "popupContent": "מחוז:יהודה ושומרון",
  "popupContent1": "יישוב:קרני שומרון",
  "popupContent2": "כתובת:רחבעם זאבי 1",
  "popupContent3": "טלפון:058-5914713",
  "popupContent4": "סוג אימון:פרטי",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 19,
  "lat": 32.10138,
  "long": 35.16750,
  "title": "שם:אשל השומרון",
  "popupContent": "מחוז:יהודה ושומרון",
  "popupContent1": "יישוב:אריאל",
  "popupContent2": "כתובת:דרך עפרון 14",
  "popupContent3": "טלפון:03-9366841",
  "popupContent4": "סוג אימון:פרטי",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 20,
  "lat": 32.07095,
  "long": 35.40346,
  "title": "שם:מועצה מקומית מעלה אפרים",
  "popupContent": "מחוז:יהודה ושומרון",
  "popupContent1": "יישוב:מעלה אפרים",
  "popupContent2": "כתובת:מעלה אפרים",
  "popupContent3": "טלפון:050-3734955",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 21,
  "lat": 32.1104,
  "long": 35.4924,
  "title": "שם:מועצה אזורית בקעת הירדן",
  "popupContent": "מחוז:יהודה ושומרון",
  "popupContent1": "יישוב:משואה",
  "popupContent2": "כתובת:משואה",
  "popupContent3": "טלפון:02-9946671",
  "popupContent4": "סוג אימון:פרטי",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 22,
  "lat": 32.03150,
  "long": 35.05738,
  "title": "שם:מו'מ בית אריה עופרים",
  "popupContent": "מחוז:יהודה ושומרון",
  "popupContent1": "יישוב:בית אריה",
  "popupContent2": "כתובת:הדולב 3",
  "popupContent3": "טלפון:02-9297714",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 23,
  "lat": 31.6415,
  "long": 35.1503,
  "title": "שם:מטווח קליבר 3 בעמ",
  "popupContent": "מחוז:יהודה ושומרון",
  "popupContent1": "יישוב:אלון שבות",
  "popupContent2": "כתובת:פארק התעשיה,גוש עציון",
  "popupContent3": "טלפון:02-6734334",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b><a href='https://www.caliber3range.com' target=_blank>לחץ כאן</a>",
},
{
  "id": 24,
  "lat": 31.41374,
  "long": 35.16243,
  "title": "שם:מוא'ז הר חברון",
  "popupContent": "מחוז:יהודה ושומרון",
  "popupContent1": "יישוב:מעון",
  "popupContent2": "כתובת:מעון",
  "popupContent3": "טלפון:02-9969118",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 25,
  "lat": 31.86425,
  "long": 35.16541,
  "title": "שם:נשק הגבעה",
  "popupContent": "מחוז:ירושלים",
  "popupContent1": "יישוב:גבעת זאב",
  "popupContent2": "כתובת:תאנה 4",
  "popupContent3": "טלפון:02-5363939",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b><a href='https://www.neshekagiva.co.il' target=_blank>לחץ כאן</a>",
},
{
  "id": 26,
  "lat": 31.77769,
  "long": 35.30092,
  "title": "שם: מטווח אדומים 2102 בעמ",
  "popupContent": "מחוז:ירושלים",
  "popupContent1": "יישוב:מעלה אדומים",
  "popupContent2": "כתובת:דרך הגיא 8",
  "popupContent3": "טלפון:02-5355555",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 27,
  "lat": 31.77879,
  "long": 35.22306,
  "title": "שם:מטווחי ירושלים בעמ",
  "popupContent": "מחוז:ירושלים",
  "popupContent1": "יישוב:ירושלים",
  "popupContent2": "כתובת:ינאי 4",
  "popupContent3": "טלפון:02-5616554",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 28,
  "lat": 31.75161,
  "long": 35.21630,
  "title": "שם:קרב מועדון קליעה וירי בעמ",
  "popupContent": "מחוז:ירושלים",
  "popupContent1": "יישוב:ירושלים",
  "popupContent2": "כתובת:יד חרוצים 13",
  "popupContent3": "טלפון:02-6722999",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 29,
  "lat": 31.73844,
  "long": 34.96373,
  "title": "שם:מטווחי פוליסיטי",
  "popupContent": "מחוז:ירושלים",
  "popupContent1": "יישוב:בית שמש",
  "popupContent2": "כתובת:וירגיניה 1",
  "popupContent3": "טלפון:02-5788537",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 30,
  "lat": 32.06273,
  "long": 34.78206,
  "title": "שם:בול מטווחים בעמ",
  "popupContent": "מחוז:תל אביב",
  "popupContent1": "יישוב:תל אביב-יפו",
  "popupContent2": "כתובת:ריב'ל 10",
  "popupContent3": "טלפון:03-6392911",
  "popupContent4": "סוג אימון:פרטי",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 31,
  "lat": 32.01435,
  "long": 34.80221,
  "title": "שם:מטווח להב בעמ",
  "popupContent": "מחוז:תל אביב",
  "popupContent1": "יישוב:חולון",
  "popupContent2": "כתובת:המשביר 1",
  "popupContent3": "טלפון:03-6876423",
  "popupContent4": "סוג אימון:פרטי",
  "url":"<b>אתר:</b> <a href='https://www.lhbltd.com' target=_blank>לחץ כאן</a>",
},
{
  "id": 32,
  "lat": 32.01559,
  "long": 34.75702,
  "title": "שם:צוקית בטחון זהב 2000 בעמ",
  "popupContent": "מחוז:תל אביב",
  "popupContent1": "יישוב:בת-ים",
  "popupContent2": "כתובת:שד יוספטל גיורא 92",
  "popupContent3": "טלפון:03-5523402",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b> <a href='https://www.zukit.co.il' target=_blank>לחץ כאן</a>",
},
{
  "id": 33,
  "lat": 31.99217,
  "long": 34.75269,
  "title": "שם:מאיר רוט בעמ",
  "popupContent": "מחוז:תרכז",
  "popupContent1": "יישוב:ראשון לציון",
  "popupContent2": "כתובת:השר שפירא משה 4",
  "popupContent3": "טלפון:03-9527063",
  "popupContent4": "סוג אימון:פרטי",
  "url":"<b>אתר:</b> <a href='https://meirroth.co.il' target=_blank>לחץ כאן</a>",
},
{
  "id": 34,
  "lat": 31.92564,
  "long": 34.87758,
  "title": "שם:אימפריאל נשק ותחמושת",
  "popupContent": "מחוז:מרכז",
  "popupContent1": "יישוב:רמלה",
  "popupContent2": "כתובת:שד הרצל 93",
  "popupContent3": "טלפון:08-92223421",
  "popupContent4": "סוג אימון:פרטי",
  "url":"<b>אתר:</b> <a href='http://www.imperialranges.co.il' target=_blank>לחץ כאן</a>",
},
{
  "id": 35,
  "lat": 31.87605,
  "long": 34.80979,
  "title": "שם:מטווח חבצלת",
  "popupContent": "מחוז:מרכז",
  "popupContent1": "יישוב:רחובות",
  "popupContent2": "כתובת:הרותם",
  "popupContent3": "טלפון:08-9415621",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b> <a href='https://mitvah-rehovot.co.il/' target=_blank>לחץ כאן</a>",
},
{
  "id": 36,
  "lat": 31.80914,
  "long": 34.66876,
  "title": "שם:ש.פ מטווחים בעמ",
  "popupContent": "מחוז:דרום",
  "popupContent1": "יישוב:אשדוד",
  "popupContent2": "כתובת:העופרת 15",
  "popupContent3": "טלפון:08-8565050",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b> <a href='https://sp-range.co.il' target=_blank>לחץ כאן</a>",
},
{
  "id": 37,
  "lat": 31.73662,
  "long": 34.72478,
  "title": "שם:מ.א רוי בעמ",
  "popupContent": "מחוז:דרום",
  "popupContent1": "יישוב:באר טוביה",
  "popupContent2": "כתובת:באר טוביה",
  "popupContent3": "טלפון:054-6440270",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 38,
  "lat": 31.51888,
  "long": 34.58047,
  "title": "שם:מטווח גלובל אנטי טרור",
  "popupContent": "מחוז:דרום",
  "popupContent1": "יישוב:קיבוץ ניר עם",
  "popupContent2": "כתובת:קיבוץ ניר עם",
  "popupContent3": "טלפון:053-7218421",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 39,
  "lat": 31.33406,
  "long": 34.39449,
  "title": "שם:קיבוץ נירים - מטווח",
  "popupContent": "מחוז:דרום",
  "popupContent1": "יישוב:קיבוץ נירים",
  "popupContent2": "כתובת:קיבוץ נירים",
  "popupContent3": "טלפון:08-9987348",
  "popupContent4": "סוג אימון:פרטי",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 40,
  "lat": 31.24208,
  "long": 34.80519,
  "title": "שם:הגברים של רתע בעמ",
  "popupContent": "מחוז:דרום",
  "popupContent1": "יישוב:באר שבע",
  "popupContent2": "כתובת:דרך חברון 60",
  "popupContent3": "טלפון:08-6450232",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b> <a href='https://www.retafirearms.com' target=_blank>לחץ כאן</a>",

},
{
  "id": 41,
  "lat": 31.26487,
  "long": 35.21162,
  "title": "שם:מטווח עירוני ערד",
  "popupContent": "מחוז:דרום",
  "popupContent1": "יישוב:ערד",
  "popupContent2": "כתובת:יאשיהו 12",
  "popupContent3": "טלפון:08-9951666",
  "popupContent4": "סוג אימון:פרטי",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 42,
  "lat": 31.00492,
  "long": 34.78627,
  "title": "שם:מטווח קב' משאבי-שדה רמת נגב",
  "popupContent": "מחוז:דרום",
  "popupContent1": "יישוב:קיבוץ משאבי שדה",
  "popupContent2": "כתובת:קיבוץ משאבי שדה",
  "popupContent3": "טלפון:050-5326407",
  "popupContent4": "סוג אימון:פרטי",
  "url":"<b>אתר:</b> <span>אין<span>",
},
{
  "id": 43,
  "lat": 29.60133,
  "long": 34.97107,
  "title": "שם:נועם-דוד בעמ",
  "popupContent": "מחוז:דרום",
  "popupContent1": "יישוב:אילת",
  "popupContent2": "כתובת:השרברב 1",
  "popupContent3": "טלפון:053-5326407",
  "popupContent4": "סוג אימון:פרטי+מאבטחים",
  "url":"<b>אתר:</b> <span>אין<span>",
}
]

let popupOption = {
  "closeButton":false
}

locations.forEach(element => {
  new L.Marker([element.lat,element.long],{icon:myIcon}).addTo(map)
  .on("mouseover",event =>{
      event.target.bindPopup(' <div class="card"> <h3>' +element.title+'</h3> <h4>' +element.popupContent+'<br>' + element.popupContent1 + '<br>'+
       element.popupContent2 + '<br>'+ element.popupContent3 + '<br>'+ element.popupContent4 + '<br>' 
       + element.url ,'</h4> </div>'  ,popupOption)
      //  .openPopup();
  })
  // .on("mouseout", event => {
  //     event.target.closePopup();
  // })
  // .on("click" , () => {
  //     window.open(element.url);
  // })
});


